### ISSUE TITLE
Ambassadord not working with Fig

### ISSUE THREAD

**Issue by HelloGrayson** [gliderlabs/connectable#10]
Given the following `fig.yml`:

```
app:
  build: .
  command: python run.py
  ports:
   - "5000"
  environment: 
    SERVICE_NAME: app

consul:
  image: progrium/consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  hostname: node1
  command: -server -bootstrap

registrator:
  image: progrium/registrator
  command: "consul://localdocker:8500"
  volumes:
    - /var/run/:/tmp/
  environment:
    SERVICE_NAME: registrator

ambassadord:
  image: progrium/ambassadord
  ports:
    - "80:10000"
  command: "app.service.consul"
```

I get the following problem with ambassadord when accessing http://localdocker/:

```
fig up ambassadord
Creating samantha_ambassadord_1...
Attaching to samantha_ambassadord_1
ambassadord_1 | 2014/10/08 23:37:11 Ambassadord listening on 10000 using app.service.consul ...
ambassadord_1 | 2014/10/08 23:37:15 dns: lookup app.service.consul on [10.0.2.3]:53: server misbehaving
ambassadord_1 | 2014/10/08 23:37:15 No backends! Closing the connection
```

Any clue would be excellent.
